提交实验报告
CUCCS/linux pull request #13
Opened 2017-03-07 05:18 UTC by AeroOwl

2017-03-07 12:22 UTC, c4pr1c3 requested changes
检查一下我的批注，微调一下即可

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +> It is best if the machine running in VirtualBox is in its own virtual network, so that I can both:
我查了一下这段英文，实际上是你直接引用的这个老外的blog啊：http://samiam.org/blog/20130826.html 为什么不顺手给出出处呢？

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +	sudo /usr/bin/software-properties-gtk --open-tab=4
你怎么可能在cli下执行成功这个命令？？

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +![](images/share.png)
普通用户可以在这样挂载的共享目录中写入数据吗？如果不能，有什么办法可以在避免使用root权限的情况下让普通用户在该共享目录下写入数据？

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +2. 用keygen.exe在Windows本地主机生成公私钥对。key passphrase处填写ubuntu远程主机的登录口令。
putygen，不是keygen

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +1. Load session, 在Data->Auto-Login username写入远程主机名。
Auto-Login username写入的是远程主机的**用户名**

2017-03-07 12:22 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +实现密码登陆：
实现**免密**登**录**

2017-03-10 06:28 UTC, AeroOwl commented on 2017-1/cay/ex1/无人值守安装iso.md
> +![](images/share.png)
用这种方法确实需要root权限。Linux和Windows共享文件夹有一种广泛使用的方法就是samba，可以修改配置使其拥有写权限，这样就能避免使用root权限吧。

再考虑VirtualBox通过GUI共享文件夹。使用时通常选择自动挂载，自动mount的文件夹的所有者为root，所属的组是vboxsf。当前用户之所以能无阻碍地使用，应该是VirtualBox实现并隐藏了一个步骤——把当前登录用户加入到vboxsf组（执行命令 sudo usermod -aG vboxsf $(whoami)）。

2017-03-10 07:49 UTC, c4pr1c3 approved these changes
well done

2017-03-10 07:49 UTC, c4pr1c3 commented on 2017-1/cay/ex1/无人值守安装iso.md
> +虽然上述方法可以使远程共享通过/mnt/shared目录使用，但是只能以root身份执行mount命令。  如果是对于普通用户，就无法在这样挂载的目录中写入数据。
把当前用户加入到vboxsf用户组就可以了

2017-03-10 07:49 UTC, merged