添加实验二：vimtutor操作全程录像以及实验一报告
CUCCS/linux pull request #14
Opened 2017-03-07 10:43 UTC by cucJ2014

2017-03-07 12:47 UTC, c4pr1c3 requested changes
看一下我的批注，微调一下再提交PR

2017-03-07 12:47 UTC, c4pr1c3 commented on 2017-1/ZYJ/LAB2/实验二：vimtutor操作全程录像.md
> +###url：[https://asciinema.org/a/9qig7fw688w2kiy9r5s27oli8](https://asciinema.org/a/9qig7fw688w2kiy9r5s27oli8 "vimtutor操作全程录像")
<del>复制粘贴操作看来你还是没有掌握啊，加油！</del>

嗯，最终还是成功了，不错！

2017-03-07 12:47 UTC, c4pr1c3 commented on 2017-1/ZYJ/LAB1/实验一：无人值守Linux安装镜像制作.md
> +保存方式：按Esc后 输入**：wq** 或者 **：x**
你这里用的是全角的冒号，应该用的是半角的冒号，我理解是你写文档时的笔误

2017-03-07 12:47 UTC, c4pr1c3 commented on 2017-1/ZYJ/LAB1/实验一：无人值守Linux安装镜像制作.md
> +密码：sec.cuc.edu.cn
再次重申：github及其他公开发表的文档中不应该出现密码

2017-03-10 07:52 UTC, c4pr1c3 approved these changes
1小时完成vimtutor，不容易，well done

2017-03-10 07:52 UTC, merged

2017-03-14 07:15 UTC, cucJ2014 commented on 2017-1/ZYJ/LAB1/实验一：无人值守Linux安装镜像制作.md
> +保存方式：按Esc后 输入**：wq** 或者 **：x**
收到~是我笔误，马上改！