第二次实验视频
CUCCS/linux pull request #20
Opened 2017-03-13 03:45 UTC by wangcuc

2017-03-16 01:28 UTC, c4pr1c3 requested changes
为什么要删除我的仓库中其他文件？给我还原回去

2017-03-17 08:42 UTC, wangcuc commented
我也不知道啊，我改的是我本地我的仓库内容啊

2017-03-19 05:40 UTC, c4pr1c3 commented
你自己点开Files changed查看，再说了，你自己看不到你自己forked之后的仓库内容对比我的主仓库缺了README和LICENSE文件吗？

2017-03-19 13:26 UTC, wangcuc commented
sorry老师这两个文件我确实没有注意，我已经恢复了，很抱歉
第三次的实验的视频录制链接已经上传，主要以阅读为主，减少录制时间我就跳过一下长的文档，后面再看

2017-03-20 06:48 UTC, c4pr1c3 requested changes
修改markdown文件名后再提交，其他内容我没意见了。

2017-03-20 06:48 UTC, c4pr1c3 commented on 2017-1/wza/ex3/实验三录制链接
> +命令学习篇，为了缩短录制时间，文档和显示结果都pass了，录制结束之后回头看
为什么你还是不习惯正确的对markdown文件进行命名呢？该有的``.md``文件扩展名你为什么偏偏要省掉呢？

2017-03-20 09:32 UTC, wangcuc commented on 2017-1/wza/ex3/实验三录制链接
> +命令学习篇，为了缩短录制时间，文档和显示结果都pass了，录制结束之后回头看
因为只有几行我就没有用markdown编辑器编辑，只用了链接的语法，可能有遗漏，我马上修改

2017-03-21 00:13 UTC, merged