上传chapter4实验代码和实验报告
CUCCS/linux pull request #32
Opened 2017-03-26 13:02 UTC by maskerwind

2017-03-29 12:02 UTC, c4pr1c3 requested changes
* bash里的字符串长度计算要考虑unicode字符的长度计算问题，也怪我题目定义不明确，通常我们提到**字符串的长度**指的是**字符的个数**，而不是**占用的字节数**。例如这样2个例子：`echo -n '中文' | wc -c`和`echo -n '中文' | wc -m`
    * http://unix.stackexchange.com/questions/160497/number-of-characters-in-a-shell-commands-output
* 读取外部文件的时候没有判断输入文件是否确实存在，直接就开始业务逻辑处理
* bash中引用变量要注意使用双引号包围，避免变量中包含空格导致代码执行出语法错误或逻辑错误

2017-03-29 12:02 UTC, c4pr1c3 commented on 2017-1/tzw/chapter4/homework-2.sh
> +  echo "      $0 -j [source(.png)] [destination(.jpg)] : switch .png/svg to .jpg"
这是一行乱入的帮助信息，你的帮助信息和你支持的命令行选项列表并不一致。少了不少参数没有说明。

另外，这个脚本考核题本身并需要做这么多命令行参数选项，你仔细读一下题目要求，并不像另外2道题那样有**交互式查询**的需求。

直接按照题目要求输出所有统计数据就对了。

题目要求计算**百分比**，你的计算结果直接四舍五入了，没有按照常规百分比计算结果那样保留小数点后2位有效数字。

2017-03-29 12:02 UTC, c4pr1c3 commented on 2017-1/tzw/chapter4/LabReport.md
> +			* i=int(pc); print (pc-i<0.5)?i:i+1
上课的时候我提示过，可以用**bc**这个命令行的任意精度计算器来实现数学运算需求。

2017-03-29 12:02 UTC, c4pr1c3 commented on 2017-1/tzw/chapter4/homework-2.sh
> +    awk -F '\t' '{if ($6~/'$max'/) {print $0} }' worldcupplayerinfo.tsv
任务要求的是：**年龄最大的球员是谁？年龄最小的球员是谁？**

你的输出结果是：

```
The Oldest Player Is :
C	Colombia	8	22	Goalie	42	50	Deportivo Cali  	Faryd Mondragon	0


The Yongest Player Is :
A	Cameroon	56	19	Forward	18	8	Zulte Waregem  	Fabrice Olinga	0
D	England	10	23	Defender	18	1	Southampton   Luke Shaw	0
```

除了名字和年龄之外，其他信息就没有必要输出了，我理解是你**懒得**处理这多余的几列信息了，反正正确答案已经包含其中了。

2017-03-29 12:02 UTC, c4pr1c3 commented on 2017-1/tzw/chapter4/homework-2.sh
> +  echo "      $0   rc     choice=+30 : Above 30-year-old"
我看了其他人脚本的运行结果，30岁以上球员是127人，你是128人，到底是谁错了呢？

2017-04-08 12:57 UTC, maskerwind commented on 2017-1/tzw/chapter4/LabReport.md
> +			* i=int(pc); print (pc-i<0.5)?i:i+1
已进行更正

2017-04-08 12:57 UTC, maskerwind commented on 2017-1/tzw/chapter4/homework-2.sh
> +    awk -F '\t' '{if ($6~/'$max'/) {print $0} }' worldcupplayerinfo.tsv
嗯。。确实是当时有些懒啦23333

2017-04-08 12:58 UTC, maskerwind commented on 2017-1/tzw/chapter4/homework-2.sh
> +  echo "      $0 -j [source(.png)] [destination(.jpg)] : switch .png/svg to .jpg"
百分比问题已更正

2017-04-08 12:58 UTC, maskerwind commented on 2017-1/tzw/chapter4/homework-2.sh
> +  echo "      $0   rc     choice=+30 : Above 30-year-old"
重复读入了数据，导致出错，已更正

2017-04-09 00:47 UTC, merged