上次交完作业后忘记pr了... = =
CUCCS/linux pull request #38
Opened 2017-03-28 15:25 UTC by Loxjan

2017-03-28 15:46 UTC, Loxjan commented
上次提交linux作业三的时候忘记PR了，这次和作业四一起PR，请老师顺带查看一下上次提交的作业三。

2017-03-29 12:19 UTC, c4pr1c3 requested changes
* bash里的字符串长度计算要考虑unicode字符的长度计算问题，也怪我题目定义不明确，通常我们提到**字符串的长度**指的是**字符的个数**，而不是**占用的字节数**。例如这样2个例子：`echo -n '中文' | wc -c`和`echo -n '中文' | wc -m`
    * http://unix.stackexchange.com/questions/160497/number-of-characters-in-a-shell-commands-output
* 读取外部文件的时候没有判断输入文件是否确实存在，直接就开始业务逻辑处理
* bash中引用变量要注意使用双引号包围，避免变量中包含空格导致代码执行出语法错误或逻辑错误

2017-03-29 12:19 UTC, c4pr1c3 commented on 2017-1/lawliet/ex3/Systemd入门学习.md
> +#Systemd入门教程
这个markdown语法真得好好再熟悉熟悉，你自己在github上预览看看有一点样子吗？

2017-03-29 14:02 UTC, Loxjan commented on 2017-1/lawliet/ex3/Systemd入门学习.md
> +#Systemd入门教程
....GitHub上的markdown样式总是和我本地有偏差...以后会注意的

2017-03-29 14:17 UTC, c4pr1c3 commented on 2017-1/lawliet/ex3/Systemd入门学习.md
> +#Systemd入门教程
这次就开始修改，注意阅读我上面给出的所有修改意见，请修改后再继续提交PR。

2017-04-09 00:49 UTC, merged