实验四修改&实验五
CUCCS/linux pull request #39
Opened 2017-04-09 03:59 UTC by CharleneTan

一、实验四修改
1. 读取外部文件的时候没有判断输入文件是否确实存在
2. 字符串长度计算更正
二、实验五

2017-04-09 10:14 UTC, c4pr1c3 requested changes
总体完成度很高，很棒！挑一个小毛病，建议完善一下再提交。

2017-04-09 10:14 UTC, c4pr1c3 commented on 2017-1/TJY/webserver/file/config.json
> +        "value":"select.*from"
这是默认的sql防护检测规则，能稍微定制复杂一些的正则式吗？这个太简陋了一些

2017-04-09 10:25 UTC, CharleneTan commented on 2017-1/TJY/webserver/file/config.json
> +        "value":"select.*from"
那个是默认的，我自己写的在config.json的第186-196行

2017-04-09 10:31 UTC, c4pr1c3 commented on 2017-1/TJY/webserver/file/config.json
> +        "value":"select.*from"
嗯，我看到了，定制了几个SQL元字符关键词。对于我的题目要求来说，你这个规则已经可以了。

但对于优秀如你来说，我还是要再给你推荐2篇文章，开阔一下眼界，看看为什么我们之前《网络安全》课程中强调SQL注入不能依赖于关键词过滤方式来防护，得依赖于预编译的SQL语句，在代码层面彻底修复SQL注入漏洞。

* https://www.owasp.org/index.php/SQL_Injection_Bypassing_WAF
* http://securityidiots.com/Web-Pentest/WAF-Bypass/waf-bypass-guide-part-1.html

基本上靠关键词过滤方式防护SQL注入是防不住的，总有办法可以绕过。

2017-04-11 05:41 UTC, c4pr1c3 approved these changes

2017-04-11 05:41 UTC, merged