第6~7章实验阶段报告
CUCCS/linux pull request #46
Opened 2017-04-17 14:00 UTC by maskerwind

已完成：
FTP、NFS、DHCP、DNS、Samba服务器、客户端的测试与使用
FTP、NFS、DHCP、DNS、Samba服务器的自动化一键搭建
TODO：
自动化搭建脚本需添加必要的异常处理
自动化搭建实验报告

2017-04-17 14:36 UTC, c4pr1c3 requested changes
总体完成度挺好的了，正如你自己总结的完成情况，看看还有没有精力继续完善还是本次作业就先这样了？给我个回复。

2017-04-17 14:36 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/workspace/script/global_conf.sh
> +server_hostonly_ip=192.168.112.20
变量赋值养成加双引号的好习惯

2017-04-17 14:36 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/workspace/script/create_user.sh
> +expect "Enter new UNIX password:"
不错！能了解到expect机制！但其实这里也可以不用expect这个重量级解决方案，直接使用更底层的添加用户程序：```useradd```，而不是高阶封装版```adduser```。

2017-04-17 14:36 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/workspace/script/init.sh
> +mkdir bak
```bash
[[ -d "bak" ]] || {
	mkdir "bak"
}
```

2017-04-17 14:36 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/workspace/script/nfs.sh
> +echo "NFS server installed"
```bash
# Linux CLI的经典哲学是：没有消息就是最好的消息！
# 所以，只要不出错，就不要打印输出！
# 出错了，打印输出错误信息和提示信息等！
ret=$? && [[ $ret -eq 0 ]] || {
	echo "NFS server installed with ret code $ret"
}
```

2017-04-17 14:51 UTC, maskerwind commented
目前正在写下一阶段的实验报告，我想能继续改善一下。

2017-04-21 07:47 UTC, c4pr1c3 requested changes
一处明显小错误之外，没有其他大问题了。

2017-04-21 07:47 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/workspace/pre_conf.sh
> +cp conf_origin/dns/db.cuc.edu.cn
这行代码明显缺第2个参数啊，你确认你提交的代码是你测试运行跑通的吗？

2017-04-21 07:49 UTC, c4pr1c3 requested changes

2017-04-21 07:49 UTC, c4pr1c3 commented on 2017-1/tzw/chapter6-7/手动配置记录.md
> +	![](\image\1.PNG)
图片的相对路径啊，不要老是用windows的路径分隔符习惯。

2017-04-24 03:04 UTC, c4pr1c3 approved these changes

2017-04-24 03:05 UTC, merged