关闭了之前的pull request，修改了之前遇到的种种问题后重新提交
CUCCS/linux pull request #5
Opened 2017-03-05 04:07 UTC by Loxjan

2017-03-06 14:17 UTC, c4pr1c3 requested changes
排版可以再更美观、正式一些。

不知道课件中其他非“实验报告”内要求的实验动手做了吗？例如：vimtutor，SSH免密登录、SSH跳板登录等等。

2017-03-06 14:17 UTC, c4pr1c3 commented on 2017-1/lawliet/ex1/创建自动化安装镜像/Loxjan.md
> +2.本次实验在宿舍自己的笔记本环境下完成，由于无法连接到sec.cuc.edu.cn/ftp下载镜像，我使用了paftp工具将原来的ubantu镜像从宿主机上传到了虚拟机来进行修改制作，最后同样适用psftp将制作好的自动化安装镜像从虚拟机下载到宿主机
错误的拼写有点多了

2017-03-06 14:17 UTC, c4pr1c3 commented on 2017-1/lawliet/ex1/创建自动化安装镜像/Loxjan.md
> +3.由于自己电脑上的镜像没有预装ssh，所以要使用putty远程连接还需要先在虚拟机内安装openssh-server.安装指令为：sudo apt-get install openssh-server ,安装完成后检查ssh是否在启动状态，如果是则可进行远程连接
如果否呢？程序员思维就是要完备。

2017-03-08 14:01 UTC, Loxjan commented on 2017-1/lawliet/ex1/创建自动化安装镜像/Loxjan.md
> +3.由于自己电脑上的镜像没有预装ssh，所以要使用putty远程连接还需要先在虚拟机内安装openssh-server.安装指令为：sudo apt-get install openssh-server ,安装完成后检查ssh是否在启动状态，如果是则可进行远程连接
如果检查出ssh没有在启动状态的话，就要在命令行输入 service ssh.service start来开启远程连接服务，开启后则可用putty进行远程操作。

2017-03-10 07:25 UTC, c4pr1c3 approved these changes
well done

2017-03-10 07:25 UTC, c4pr1c3 commented on 2017-1/lawliet/ex2/Linux命令行基础.md
> +为了避免视频冗余过大，本次录制分为七次，分别按照vimtutor教程上的课程来划分，方便老师审查
有心了，👍

2017-03-10 07:26 UTC, merged