Exp for Chapter8
CUCCS/linux pull request #51
Opened 2017-04-30 06:16 UTC by maskerwind

2017-05-02 03:11 UTC, c4pr1c3 requested changes
相关配置脚本请一并上传了，你可以看一下其他已经完成作业同学的做法，不要在markdown文件里粘贴脚本源代码。

我们上课布置作业时说明过的要求是：可以让任何人在检出代码之后，在本地实验环境只需要修改hosts文件中定义的目标主机IP和必要的ansible部署前设置准备，就可以完成对测试环境中主机部署服务的效果。

2017-05-02 03:11 UTC, c4pr1c3 commented on 2017-1/tzw/chapter8/第八章实验报告--Ansible.md
> +		        smbpasswd: '123'
这种明文口令，而且是弱口令的方式特别不好。建议你看一下我在这个PR https://github.com/CUCCS/linux/pull/49 里的评论。

2017-05-02 03:11 UTC, c4pr1c3 commented on 2017-1/tzw/chapter8/第八章实验报告--Ansible.md
> +		         password: '123'
同样的问题，弱口令、配置文件中的明文口令。

2017-05-08 12:21 UTC, c4pr1c3 requested changes
按照我的提示修改了再试试

2017-05-08 12:21 UTC, c4pr1c3 commented on 2017-1/tzw/chapter8/ansible/roles/franklinkim.vsftpd/tasks/users.yml
> +  with_items: "{{vsftpd_users}}"
`vsftpd_users`的两边空格呢？

2017-05-08 12:21 UTC, c4pr1c3 commented on 2017-1/tzw/chapter8/第八章实验报告--Ansible.md
> +		fatal: [192.168.112.20]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.
错误提示信息非常清楚，看我上面的评论，应该是你引用`username`的语法使用错误

2017-05-10 10:20 UTC, maskerwind commented on 2017-1/tzw/chapter8/第八章实验报告--Ansible.md
> +		fatal: [192.168.112.20]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.
按照老师的提示把with_items: "{{vsftpd_users}}"改为with_items: "{{ vsftpd_users }}"，依旧会出现该错误。但是这个错误在不使用--ask-vault-pass参数的情况下不会出现；另外尝试了不使用vault的变量加密方式而只是使用vault文件加密，是可以成功的。

2017-05-11 01:09 UTC, c4pr1c3 commented on 2017-1/tzw/chapter8/第八章实验报告--Ansible.md
> +		fatal: [192.168.112.20]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.
vault的变量加密方式是从ansible 2.3才开始支持的，你检查一下本地的ansible版本是不是支持。文件加密方式是从1.5版本开始就有了，所有稳定性肯定是最好。

2017-05-11 01:10 UTC, c4pr1c3 approved these changes

2017-05-11 01:10 UTC, merged